apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
    - name: demo
      image: busybox
      command:
        [
          "sh",
          "-c",
          "cat /etc/secrets/username && cat /etc/secrets/password && sleep 3600",
        ]
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: volume-secret
