apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: busybox
      command:
        ["sh", "-c", "echo $APP_COLOR && echo $WELCOME_MSG && sleep 3600"]
      envFrom:
        - configMapRef:
            name: sample-config
