apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo HostPath >> /host/log.txt && sleep 3600"]
      volumeMounts:
        - name: host-volume
          mountPath: /host
  volumes:
    - name: host-volume
      hostPath:
        path: /tmp/k8s-hostpath
        type: DirectoryOrCreate
