apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        ["sh", "-c", "ls /etc/secret && cat /etc/secret/username && sleep 3600"]
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
