apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-config
data:
  myvalue: "これはConfigMapからのデータです"

---
apiVersion: v1
kind: Pod
metadata:
  name: volume-demo-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "cat /config/myvalue && sleep 3600"]
      volumeMounts:
        - name: emptydir-volume
          mountPath: /cache
        - name: config-volume
          mountPath: /config
  volumes:
    - name: emptydir-volume
      emptyDir: {}
    - name: config-volume
      configMap:
        name: sample-config
