apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # 外部アクセス用のタイプ
  selector:
    app: nginx # Podのラベルセレクター（pod.yamlのlabelsと合わせる）
  ports:
    - port: 80 # Serviceのポート
      targetPort: 80 # Podのコンテナポート
      nodePort: 30080 # 外部からアクセスする際のポート（30000-32767の範囲）
